/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be committed alongside the rest of your project.
// It is generated by Expo and ensures type-safety across the project.
